---
- block:
  - name: Create registry pod directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
    loop:
      - /opt/registry/certs
      - /opt/registry/data

  - name: Create the local registry pod for images
    ansible.builtin.command: >-
      podman run -d --name registry
      -p 5000:5000
      -v /opt/registry/data:/var/lib/registry:z
      -v /opt/registry/certs:/certs:z
      -e "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt"
      -e "REGISTRY_HTTP_TLS_KEY=/certs/registry.key"
      --restart always
      docker.io/library/registry:2

  - name: Configure podman to allow insecure registry
    ansible.builtin.copy:
      content: |
        [[registry]]
        location = "registry:5000"
        insecure = true
      dest: /etc/containers/registries.conf.d/insecure-registry.conf
      mode: '0644'
  delegate_to: registry