---
- block:
  - name: Install skopeo
    ansible.builtin.package:
      name: skopeo
      state: present

  - name: Create registry pod directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
    loop:
      - /opt/registry/certs
      - /opt/registry/data

  - name: Create the local registry pod for images
    ansible.builtin.command: >-
      podman run -d --name registry
      -p 5000:5000
      -v /opt/registry/data:/var/lib/registry:z
      --restart always
      docker.io/library/registry:2

  - name: Configure podman to allow insecure registry
    ansible.builtin.copy:
      content: |
        [[registry]]
        location = "localhost:5000"
        insecure = true
      dest: /etc/containers/registries.conf.d/insecure-registry.conf
      mode: '0644'

  - name: Mirror images to local registry
    ansible.builtin.include_tasks: mirror_images.yml
    when: registry_mirror_images | default(true)

  delegate_to: registry
